name: Maven Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run tests with sampleTests profile
        run: mvn test -P sampleTests

      - name: Generate Test Report
        run: mvn surefire-report:report-only

      - name: Install xsltproc
        run: sudo apt-get install xsltproc

      - name: Convert XML to HTML
        run: xsltproc /path/to/stylesheet.xsl target/site/surefire-report.html target/surefire-reports/*.xml

      - name: Archive Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/site/surefire-report.html

      - name: Send email with test report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Maven Test Results
          body: Please find the attached test report.
          to: recipient@example.com
          from: sender@example.com
          content_type: text/html
          attachments: target/site/surefire-report.html
